### PR TITLE
chore: Clean up of unused modules

### PR DESCRIPTION
**Pull request by uchukwu**
A continuation to [this PR](https://github.com/mbta/commuter_rail_boarding/pull/189)

- Further clean-up of unused modules: (1) TrainLoc.Logging and (2) TrainLoc.Vehicles.Validator

### CODE REVIEW

**Comment by losvedir** [comment]
I don't think I ever set expectations here, but to complete this task I'm thinking that something like ~50% or more of the existing code in `apps/train_loc/lib` can be deleted. i.e.: far, far more than what you've done so far. I don't want to find all the code myself and enumerate the modules here, because figuring out which code is used and which isn't, is essentially what this ticket is.

To start, you can delete the mix tasks in `lib/mix/tasks/*` which we never use, and their tests.

Then, basically, start looking at modules, and trying to search the codebase for where they are used. If a module is only ever referenced in a test file, then it can be deleted, together with any tests that relate to it.

If you have questions about whether a given module is used, feel free to ask in Slack. For example, something like `TrainLoc.Vehicles.State` - which is something I explicitly called out in the task description, and then again in the follow-up comment - can and still should be deleted. But that one is actually referenced a little bit: it's listed as a child that the `Supervisor` watches. But since it's not used otherwise, we can remove it from the Supervisor, too.

**Comment by uchukwu** [comment]
`TestHelpers` doesn't appear to be referenced by any code in codebase, but it's required for `mix test`. Hence, I did not remove that one in particular

**Review by losvedir — APPROVED** [review]
🎉

**Comment by uchukwu** [comment]
> 🎉

This ready for merge?

**Comment by losvedir** [comment]
Yep, merge away!

**Pull request merged**
